CREATE DATABASE AppTraSua
GO
USE AppTraSua
GO

--drop table [USER]
CREATE TABLE [USER](
	[UserID] [int] identity(1,1) NOT NULL,
	[UserName] [varchar](25) NOT NULL,
	[Password] [varchar](25) NOT NULL,
	[isActive] [bit] NOT NULL,
	[GroupID] [int] NULL,
 CONSTRAINT [PK_USER_UserID] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)
)
GO
--drop table [USERGROUP]
CREATE TABLE [USERGROUP](
	[GroupID] [int] identity(1,1) NOT NULL,
	[GroupName] [nvarchar](25) NULL,
 CONSTRAINT [PK_USERGROUP_GroupID] PRIMARY KEY CLUSTERED 
(
	[GroupID] ASC
)
) 
GO
--drop table [PRODUCT]
CREATE TABLE [PRODUCT](
	[ProductID] [int] identity(1,1) NOT NULL,
	[ProductName] [nvarchar](50) NULL,
	[isActive] [bit] NOT NULL,
	[Price] [int] NOT NULL,
	[ProTypeID] [int] NULL,
	[Popular] [float] NULL,
 CONSTRAINT [PK_MENU_ID] PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)
) 
GO
--drop table [PRO_TYPE]
CREATE TABLE [PRO_TYPE](
	[ProTypeID] [int] identity(1,1) NOT NULL,
	[Name] [nvarchar](25) NULL,
 CONSTRAINT [PK_GROUPMENU_GroupMenuID] PRIMARY KEY CLUSTERED 
(
	[ProTypeID] ASC
)
) 
GO
--drop table [CUS_TYPE]
CREATE TABLE [CUS_TYPE](
	[CusTypeID] [int] identity(1,1) NOT NULL,
	[Name] [nvarchar](25) NULL,
 CONSTRAINT [PK_AREA_AreaID] PRIMARY KEY CLUSTERED 
(
	[CusTypeID] ASC
)
)
GO
--drop table [BILL]
CREATE TABLE [BILL](
	[BillID] [int] identity(1,1) NOT NULL,
	[Date] [datetime] NULL,
	[CusTypeID] [int] NULL,
	[TotalAmout] [int] NULL,
 CONSTRAINT [PK_TICKET_TicketID] PRIMARY KEY CLUSTERED 
(
	[BillID] ASC
)
)
GO
--drop table [BILLDETAIL]
CREATE TABLE [BILLDETAIL](
	[BillDetailID] [int] identity(1,1) NOT NULL,
	[BillID] [int] NOT NULL,
	[ProductID] [int] NOT NULL,
	[BDQuantity] [int] NULL,
	[BDTotalAmout] [int] NULL,
 CONSTRAINT [PK_TICKETDETAIL_TicketDetailID_TicketID] PRIMARY KEY CLUSTERED 
(
	[BillDetailID] ASC,
	[BillID] ASC
)
)
GO

CREATE TABLE [TEMPNUMBER](
	[NextBillID] [int] NULL,
)
GO


ALTER TABLE [USER]
ADD CONSTRAINT FK_USER_USERGROUP
FOREIGN KEY (GroupID)
REFERENCES [USERGROUP](GroupID)
GO
ALTER TABLE [BILL]
ADD CONSTRAINT FK_BILL_CUS_TYPE
FOREIGN KEY (CusTypeID)
REFERENCES [CUS_TYPE](CusTypeID)
GO
ALTER TABLE [BILLDETAIL]
ADD CONSTRAINT FK_BILLDETAIL_BILL
FOREIGN KEY (BillID)
REFERENCES [BILL](BillID)
GO
ALTER TABLE [BILLDETAIL]
ADD CONSTRAINT FK_BILLDETAIL_PRODUCT
FOREIGN KEY (ProductID)
REFERENCES [PRODUCT](ProductID)
GO
ALTER TABLE [PRODUCT]
ADD CONSTRAINT FK_PRODUCT_PRO_TYPE
FOREIGN KEY (ProTypeID)
REFERENCES [PRO_TYPE](ProTypeID)
GO
/*USE master
GO
DROP DATABASE AppTraSua*/
GO