USE AppTraSua
GO

--nhập liệu
INSERT INTO dbo.[USERGROUP]([GroupName]) VALUES (N'Quản lý')
INSERT INTO dbo.[USERGROUP]([GroupName]) VALUES (N'Thu ngân')
GO
INSERT INTO dbo.[USER]([UserName], [Password], [isActive], [GroupID]) VALUES ('thungan01', 'AXXXZZ1234-AZA', 1, 2)
INSERT INTO dbo.[USER]([UserName], [Password], [isActive], [GroupID]) VALUES ('thungan02', 'AXXXZZ1234-AZA', 1, 2)
INSERT INTO dbo.[USER]([UserName], [Password], [isActive], [GroupID]) VALUES ('QUANLY', 'AXXXZZ1234-AZA', 1, 1)
GO
INSERT INTO dbo.[PRO_TYPE]([Name]) VALUES (N'Trà sữa')
INSERT INTO dbo.[PRO_TYPE]([Name]) VALUES (N'Trà nguyên chất')
INSERT INTO dbo.[PRO_TYPE]([Name]) VALUES (N'Thức uống sáng tạo')
INSERT INTO dbo.[PRO_TYPE]([Name]) VALUES (N'Thức uống đá xay')
INSERT INTO dbo.[PRO_TYPE]([Name]) VALUES (N'Thức uống đặc biệt')
INSERT INTO dbo.[PRO_TYPE]([Name]) VALUES (N'Thức uống khác')
INSERT INTO dbo.[PRO_TYPE]([Name]) VALUES (N'Topping')
GO
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Sữa Tươi Okinawa - M', 1, 47000, 6)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Sữa Tươi Okinawa - L', 1, 53000, 6)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Strawberry Earl Grey Latte - M', 1, 57000, 6)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Strawberry Earl Grey Latte - L', 1, 63000, 6)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Mango Matcha Latte - M', 1, 57000, 6)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Okinawa Latte - M', 1, 51000, 6)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Okinawa Latte - L', 1, 57000, 6)

INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Bí Đao Kem Sữa - M', 1, 47000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Bí Đao Kem Sữa - L', 1, 53000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Oolong Kem Sữa - M', 1, 47000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Oolong Kem Sữa - L', 1, 53000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Oolong Kem Sữa - Nóng', 1, 47000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Earl Grey Kem Sữa - M', 1, 47000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Earl Grey Kem Sữa - L', 1, 53000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Đen Kem Sữa - M', 1, 43000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Đen Kem Sữa - L', 1, 49000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Đen Kem Sữa - Nóng', 1, 43000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh Kem Sữa - M', 1, 43000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh Kem Sữa - L', 1, 47000, 5)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh Kem Sữa - Nóng', 1, 43000, 5)

INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Xoài Trân Châu Đen - M', 1, 51000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Xoài Trân Châu Đen - L', 1, 57000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Xoài Trân Châu Đen - Nóng', 1, 51000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Okinawa - M', 1, 51000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Okinawa - L', 1, 57000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Okinawa - Nóng', 1, 51000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Matcha Đậu Đỏ - M', 1, 53000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Matcha Đậu Đỏ - L', 1, 59000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Matcha Đậu Đỏ - Nóng', 1, 53000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà sữa Oolong 3J - M', 1, 53000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà sữa Oolong 3J - L', 1, 59000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Pudding Đậu Đỏ - M', 1, 47000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Pudding Đậu Đỏ - L', 1, 53000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Chocolate - M', 1, 47000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Chocolate - L', 1, 53000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Chocolate - Nóng', 1, 47000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Trân Châu Đen - M', 1, 43000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Trân Châu Đen - L', 1, 49000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Trân Châu Đen - Nóng', 1, 43000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Hokkaido - M', 1, 43000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Hokkaido - L', 1, 49000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Cà Phê - M', 1, 43000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Cà Phê - L', 1, 49000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Cà Phê - Nóng', 1, 43000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Sương Sáo - M', 1, 43000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Sương Sáo - L', 1, 49000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Oolong - M', 1, 43000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Oolong - L', 1, 49000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Oolong - Nóng', 1, 43000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Trà Đen - M', 1, 40000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Trà Đen - L', 1, 46000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Trà Đen - Nóng', 1, 40000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Trà Xanh - M', 1, 40000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Trà Xanh - L', 1, 46000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Trà Xanh - Nóng', 1, 40000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Khoai Môn - M', 1, 47000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Khoai Môn - L', 1, 53000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Earl Grey - M', 1, 43000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Earl Grey - L', 1, 49000, 1)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Sữa Earl Grey - Nóng', 1, 43000, 1)

INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Bí Đao Alisan - M', 1, 36000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Bí Đao Alisan - L', 1, 42000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Bí Đao - M', 1, 36000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Bí Đao - L', 1, 42000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan - M', 1, 36000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan - L', 1, 42000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan - Nóng', 1, 36000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Earl Grey - M', 1, 36000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Earl Grey - L', 1, 42000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Earl Grey - Nóng', 1, 36000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Oolong - M', 1, 36000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Oolong - L', 1, 42000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Oolong - Nóng', 1, 36000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Đen - M', 1, 33000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Đen - L', 1, 39000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Đen - Nóng', 1, 33000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh - M', 1, 33000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh - L', 1, 39000, 2)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh - Nóng', 1, 33000, 2)

INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'QQ Chanh Dây Trà Xanh - M', 1, 47000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'QQ Chanh Dây Trà Xanh - L', 1, 53000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Chanh Ai-yu và Trân Châu Trắng - M', 1, 43000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Chanh Ai-yu và Trân Châu Trắng - L', 1, 49000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Đào Hồng Mận Hạt É - M', 1, 43000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Đào Hồng Mận Hạt É - L', 1, 49000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Oolong Vải - M', 1, 43000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Oolong Vải - L', 1, 49000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan Vải - M', 1, 43000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan Vải - L', 1, 49000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan Vải - Nóng', 1, 43000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan Xoài - M', 1, 43000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan Xoài - L', 1, 49000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan Xoài - Nóng', 1, 43000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh Chanh Dây - M', 1, 43000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh Chanh Dây - L', 1, 49000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh Chanh Dây - Nóng', 1, 43000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan Chanh Dây - M', 1, 40000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan Chanh Dây - L', 1, 46000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Alisan Chanh Dây - Nóng', 1, 40000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Đen Đào - M', 1, 40000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Đen Đào - L', 1, 46000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Đen Đào - Nóng', 1, 40000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh Đào - M', 1, 40000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh Đào - L', 1, 46000, 3)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trà Xanh Đào - Nóng', 1, 40000, 3)

INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Strawberry Oreo Smoothie - M', 1, 63000, 4)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Chocolate Đá Xay - M', 1, 59000, 4)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Khoai Môn Đá Xay - M', 1, 59000, 4)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Matcha Đá Xay - M', 1, 59000, 4)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Yakult Đào Đá Xay - M', 1, 59000, 4)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Xoài Đá Xay - M', 1, 54000, 4)

INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Kem Sữa', 1, 16000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Nha Đam', 1, 10000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Hạt É', 1, 10000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trân Châu Đen', 1, 10000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Trân Châu Trắng', 1, 10000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Đậu Đỏ', 1, 10000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Sương Sáo', 1, 10000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Thạch Nâu', 1, 10000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Thạch Trái Cây', 1, 10000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Thạch Ai-yu', 1, 10000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Thạch Dừa', 1, 10000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Pudding', 1, 10000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Combo 2 Loại Hạt', 1, 17000, 7)
INSERT INTO dbo.[PRODUCT]([ProductName], [isActive], [Price], [ProTypeID]) VALUES (N'Combo 3 Loại Hạt', 1, 25000, 7)

GO
INSERT INTO dbo.[CUS_TYPE]([Name]) VALUES (N'Giao hàng')
INSERT INTO dbo.[CUS_TYPE]([Name]) VALUES (N'Khu uống tại quán')
GO
INSERT INTO dbo.[TEMPNUMBER]([NextBillID]) VALUES (1)